/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Abc: typeof import('./pages/dashboard/components/abc.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    Dark: typeof import('./components/Dark.vue')['default']
    FooterContent: typeof import('./components/FooterContent.vue')['default']
    Language: typeof import('./components/Language.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./components/SideMenu.vue')['default']
  }
}
